### ISSUE TITLE
[Documentation] README.txt contains wrong instructions

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/tools-distribution#158]
This is applicable to the README.txt in the 0.93 release pack

Quote:
```
Run the Composer
----------------

1. At the command prompt, type: composer
2. Access the Composer from the following URL in your browser: http://localhost:9091
```
But here there is no indication that the path variable should be set for the above 1st point to work. Inside the Run HelloWorld section, its mentioned to set the path. This information should be high level.

Furthermore the README.txt should be structured so that the user has easiness in finding information on how to do the first steps with Ballerina

**Comment by yasassri** [comment]
The PR is merged hence closing.
